test
Konkuk-KUIT/KUIT4_Web-FrontEnd pull request #28
Opened 2024-09-24 06:22 UTC by heeeeyong

## 📚 워크북 링크

## 📝 변경/추가 사항 요약

## ✅ 리뷰 요구사항
노트북 바꿨는데 해당에러가 계속떠서 브랜치를 새로 만들었습니다... 
지금 보기엔 해결이 된 것 같은데 다른 기기에서도 이전에 쓰던 같은 브랜치를 사용 할 순 없나요?
## 📸 확인 방법 (스크린샷)
![image](https://github.com/user-attachments/assets/85c710de-4119-4e21-8ca6-81b72bd3e6b8)

2024-09-26 16:39 UTC, Turtle-Hwan requested changes
- 실습코드와 구분을 위해 week2/heeedragon 안에 미션용 / 실습용 폴더를 각각 만드셔서 그 안에다 index.html로 따로 넣어주세요!

2024-09-26 16:39 UTC, Turtle-Hwan commented on week2/heeedragon/daangn/practice.css
> +}
- 질문해주셨던 오른쪽 아래 댓글과 하트 배치는, 이 `.product__info` 안에 width: 100%를 넣으면 해결됩니다!
- flex 등에서 width를 가득 채우고 싶다면 명시적으로 넣어주어야 합니다.

2024-09-26 16:39 UTC, Turtle-Hwan commented on week2/heeedragon/daangn/practice.css
> +}
추가적으로, 아래에 붙이기 위해 이 속성을 넣으면 좋을 것 같아요
`justify-content: space-between;`

flex와 grid는 부모 tag에 속성을 주면 자식들이 영향받는 구조라 이를 생각해보면 좋을 거 같습니다

2024-09-26 16:39 UTC, Turtle-Hwan commented on week2/heeedragon/daangn/practice.html
> +        </button>
- 해당 plus 버튼은 화면 스크롤에 관계없이 항상 하단에서 보여야 하니 하단 바로 생각해보는 것은 어떨까요?
- 하단 바에 포함시켜서 혹은 옆에 두고 fixed를 적용해보는 것도 좋을 거 같아요

2024-09-26 16:40 UTC, Turtle-Hwan commented on week2/heeedragon/daangn/practice.html
> +        </button>
상단 바에도 fixed가 적용되어 있지 않네요! 적용시켜 주시면 좋을 거 같슴니다

2024-09-27 07:43 UTC, heeeeyong commented on week2/heeedragon/daangn/practice.html
> +        </button>
감사합ㅎ니당

2024-09-27 08:06 UTC, heeeeyong commented
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ce5ba55d-76bd-4ded-86e7-06677cae75db">

1. +버튼 하단바에 추가하여 위치 지정 완료
2. 상품 사이 border-bottom 길이 부모 컨테이너 길이 따라가게끔 수정
3. 상단바 fixed 완료
4. 부모컨테이너 width 100% 주어 댓글과 좋아요 우측하단에 배치 완료

2024-09-28 07:22 UTC, Turtle-Hwan approved these changes
제가 폴더 정리한다고 commit 하나 남겨서,
다음 번에 진행하실 땐 git pull 한 번 받아주시고 commit 쌓아주시면 될 거 같아요~! 고생 많으셨고 머지하겠습니다~!

2024-09-28 07:22 UTC, Turtle-Hwan commented on week2/heeedragon/daangn/미션용/index.html
> +
여기에 아마 </div> 닫는 태그 하나 빠진 거 같아요 확인 부탁해요~

2024-09-28 07:22 UTC, Turtle-Hwan commented on week2/heeedragon/daangn/미션용/index.css
> +
margin으로 처리하신 점 좋습니다~!

추가로 [이 리뷰](https://github.com/Konkuk-KUIT/KUIT4_Web-FrontEnd/pull/29#discussion_r1776993357)와 동일 의견입니다!

2024-09-28 07:23 UTC, merged

2024-09-29 03:39 UTC, heeeeyong commented on week2/heeedragon/daangn/미션용/index.css
> +
넵! 확인했슴다~

2024-09-29 03:41 UTC, heeeeyong commented on week2/heeedragon/daangn/미션용/index.html
> +
맞네요! 확인했습니다~