[2주차] 당근마켓 화면1 미션
Konkuk-KUIT/KUIT4_Web-FrontEnd pull request #31
Opened 2024-09-24 19:33 UTC by hyun1211

## 📚 워크북 링크
https://broad-stargazer-e56.notion.site/2-CSS-10a29a65c45880788d62d39d8c9ef41c?pvs=4
## 📝 변경/추가 사항 요약
당근마켓 화면1 미션 레이아웃 작성
## ✅ 리뷰 요구사항
- bottom-menu의 CSS에서, 분명 가운데 정렬효과를 적용했는데 왜 적용안된건지 궁금합니다. 
## 📸 확인 방법 (스크린샷)
![img](https://github.com/user-attachments/assets/72965e94-584d-4310-a69d-a16777699bcb)

2024-09-26 10:48 UTC, NekoNyangYee commented
아이콘과 라벨을 div태그로 감싸서 css 스타일에 display: flex; flex-driection: column; 주시고 아이콘 부분만 따로 margin: 0 auto;로 해보세여

2024-09-26 16:19 UTC, danpung628 commented
+버튼을 추가했습니다.

2024-09-26 17:30 UTC, Turtle-Hwan requested changes
열심히 구현해주셨고 고생 많으셨습니다!
다만 손봐야 할 곳이 조금 있는 것 같습니다. 다른 분들 코드도 참고하시면서 수정 부탁드리겠습니다!!

하단 바의 경우 태현님이 잘 답변해주신 것 같습니다!

리뷰 내용에서 궁금증이 생기면 여기에 댓글 달아주세요!

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +    overflow-y: auto;
box-sizing: border-box 옵션도 body에 넣어주시면 좋습니다

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +.top-menu {
- top menu도 하단 바처럼 fixed로 넣어주면 좋아요
- 여기에 border-bottom도 주시면 figma와 동일해질 거 같습니다

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +    height: 778px;
여기서 height도 제한하고 main-contents에서도 margin-bottom도 줘서 두 개로 조절하기보다는 margin-bottom 하나만으로 통일하면 더 좋지 않을까요?

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +}
- 여기에 margin을 많이 줘서 끝에 오도록 조절하는 것 보다는, 여기서 margin을 없애고, 부모 요소(top-menu)에 
```
justify-content: space-between;
align-items: center;
```
이 속성들을 주면 더 깔끔하게 좌우로 붙일 수 있어요.

- 게다가 이 친구는 내부에 있는 element이니까 margin이 의도한 요소 바깥으로 튀어나가는 것은 그리 좋지 않은 것 같습니다.

- display flex를 주신 건 사이에 gap도 주시려고 하신 것이겠죠?

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +}
- 세부 요소가 필수적으로 width가 지정되어야 하는 경우 (ex. image 등)이 아닌 경우에 width를 고정 값으로 넣는 것은 지양하면 좋습니다. 반응형으로 바꿀 때 상당히 힘들어질 수 있거든요..

- main-article에서 `justify-content: flex-start;` 를 주시고, 여기에 `width:100%`를 주시면 더 깔끔하겠죠?

- 마찬가지로 여기에 
```
display:flex;
flex-direction: column;
```
를 주시는 것이 안쪽 요소들 배치에 더 좋지 않을까요?

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +}
- 여기에 flex 가로 배열로 배치하는 것도 좋은 방법이지만, 하위 요소들을 span으로 만들었다면 inline 요소라 가로 배치 되는 방법도 있어요

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +}
- margin 고정값으로 원하는 곳에 배치하기는 상당히 어렵습니다
- 어느 한 쪽 끝에 붙이고 싶을 때는 flex-end와 width:100%를 함께 쓰면 좋습니다.
- 아까 이 친구의 상위 요소인 article1-desc 의 width를 100%로 두었다면, 여기서는 width 속성을 아예 안 주면 자동으로 부모 것을 받아와 꽉 차게 되겠죠?

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +}
이 친구를 맨 아래로 붙이고 싶다면, 위 요소 3개를 따로 묶고 이 요소를 따로 묶어서,
 이 두 개를 포함한 flex를 주어 위아래로 붙여버리면 좋겠죠?

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +    width:390px;
- 이렇게 bottom-menu와 contents 에 따로 width를 고정값으로 주게 되면 사이에 fixed button을 넣거나 반응형으로 바꿀 때 많이 힘들어질 수 있습니다.

- 고정값 width는 최대한 최상위 container에서 한 번만 주거나,
최상위 container에서 margin 값을 주는 방식으로 처리하면 좋습니다

2024-09-26 17:30 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +}
- 현재 해당 요소는 width가 전체 뷰포트의 width로 판단되어서 이상한 곳에 fixed가 박히는 현상이 발생합니다.

- 어떻게 해결 가능할까요?
- width를 원하는 만큼 줄이고 그 안에서 fixed를 주거나, 원래 고정 값이엇던 bottom bar에 포함시키는 방법도 가능할까요?

2024-09-27 16:53 UTC, hyun1211 commented on package-lock.json
길고 자세한 리뷰 정말 감사드립니다!!!!

2024-09-28 07:32 UTC, Turtle-Hwan commented on package-lock.json
main 폴더에 있는 걸 삭제해달란 뜻이었는데 제가 지웠습니다~
있어도 큰 문제는 없지만 혹시나 해서요

다음에 수정하실 때 git pull 받아주세요~

2024-09-28 07:33 UTC, Turtle-Hwan commented on week2/hyunju/index.css
> +.top-menu {
추가 리뷰>
- border bottom 색깔도 figma랑 맞춰주세요!
- fixed로 줬다면 아래 content가 가려지기 때문에 main-content에 margin-top 속성을 주어야 합니다!

2024-09-28 07:40 UTC, Turtle-Hwan approved these changes
- content 사이사이를 구분해주는 경계선도 빠져 있는 것 같습니다~!
- main-content의 margin-bottom과 button의 bottom 공간이 조금 넓은 거 같다는 생각이 드네요!
- fixed 속성을 plus button과 이를 감싸는 fixed-button 두 개 다에 주기보다는 제일 바깥쪽 fixed-button 요소 하나에만 주는 것이 좋아 보입니다!
![image](https://github.com/user-attachments/assets/86ffe02d-cc0d-4c08-bb14-344da434fc58)

2024-10-03 10:19 UTC, merged