[1주차] 자기소개 HTML
Konkuk-KUIT/KUIT4_Web-FrontEnd pull request #9
Opened 2024-09-16 11:33 UTC by Hwanggyuun

## 📚 워크북 링크
https://tangy-light-cf4.notion.site/1-10217e4d8cd080efbdc2fe33f1310415?pvs=4

## 📝 변경/추가 사항 요약
-HTML

## ✅ 리뷰 요구사항

## 📸 확인 방법 (스크린샷)
![image](https://github.com/user-attachments/assets/b9e41a58-1972-4696-a500-358e397560f2)

2024-09-16 11:51 UTC, Turtle-Hwan reviewed
잘 해주셨습니다.

리뷰에 대한 코드 수정은,
해당 브랜치에 추가로 커밋한 후 push 하면 열린 PR에 자동 반영됩니다!

2024-09-16 11:51 UTC, Turtle-Hwan commented on week1/gyuunindex.html
> +    <title>1주차 실습 : turtlehwan 자기소개</title>
와 1등으로 PR 해주셨네요
빠른 첫 PR 아주 좋습니다~!

다만 여기 부분이 turtlehwan으로 되어 있네요! 
Hwanggyuun 등 자신을 나타낼 수 있는 이름으로 바꾸면 더욱 좋을 거 같아요
```suggestion
    <title>1주차 실습 : Hwanggyuun 자기소개</title>
```

2024-09-16 11:51 UTC, Turtle-Hwan commented on week1/gyuunindex.html
> +    <div>하고 싶은 말2 : 아무도 나를 막을 수 없다.</div>
- 필수는 아니지만 추천 사항입니다.

영상에서도 전부 div 태그로 설명드리긴 했지만.. h1, h2 등 다양한 태그를 써보는 것도 좋고,      
워크북에 있는 display block 속성과 inline속성의 차이를 div 태그와 span 태그를 직접 써보면서 알아봐도 좋을 것 같아요

2024-09-17 05:27 UTC, Jinho1011 requested changes

2024-09-17 05:27 UTC, Jinho1011 commented on week1/turtlehwan/index.html
> +    <div>하고 싶은 말2 : 아무도 나를 막을 수 없다.</div>
지환님꺼도 같이 수정된거 같아요~! 롤백 부탁드려욤

2024-09-19 08:09 UTC, Turtle-Hwan approved these changes
와 고생하셨습니다~!!

2024-09-19 08:18 UTC, Turtle-Hwan commented on week1/turtlehwan/index.html
> +    <div>하고 싶은 말2 : 아무도 나를 막을 수 없다.</div>
[156976f](https://github.com/Konkuk-KUIT/KUIT4_Web-FrontEnd/pull/9/commits/156976f1a4ef6ab7e16019e0f6a74eedc368c4a1)

2024-09-19 08:19 UTC, merged